                                            NUMPY_NCERT_BASIC

                                CASE STUDY ON IRIS DATASET ref. NCERT 

 1.         --  Numpy basically stand for Numerical Pandas- its package for data analysis and scientific computing

In [1]:
# installation can be done using the follwing command in terminal like cmd
#pip install NumPy

2.-- data types - we can say user defined and inbuilt data types 
     inbuilt data types - dict, list ,tuple etc 
     user defind data types -  arrays, class, structure, union, Enumeration,
     pointer, etc


3.-- NumPy Array
    NumPy arrays are used to store lists of numerical data, vectors and 
    matrices 


5. -- Creation of numpy Array from list


In [2]:
# importing libraries 
import numpy as np


In [3]:
# create an array 
# lets say 
array1 = np.array([10,20,30])
array1

array([10, 20, 30])

In [4]:
# 1-D array 

array2 = np.array([5,-7.4,'a',7.2])
array2
# here dtypes u32 means unicode 32


array(['5', '-7.4', 'a', '7.2'], dtype='<U32')

Attributes of array 
ndarray.ndim: gives the number of dimensions of the array as an integer value

In [5]:
# dimesion of array 
array2.ndim

1

In [6]:
array1.shape

(3,)

In [7]:
array3 = np.array([[2.4,3],[4.91,7],[0,-1]])

In [8]:
array3.ndim

2

In [9]:
array3.shape # gives the sequence of integer indicating sixe of the array in each dimesion

(3, 2)

In [10]:
array3.size # gives total no of elements

6

In [11]:
array3.dtype  #print data types of element

dtype('float64')

In [12]:
array1.itemsize # specifies the size in bytes of each item of the array 

4

alternative way  to create Arrays

In [13]:
array4 = np.array([[1,2],[3,4],[4,5]],dtype =float)

In [14]:
array4

array([[1., 2.],
       [3., 4.],
       [4., 5.]])

In [15]:
array4.ndim

2

In [16]:
array4.size

6

In [17]:
 zero_array = np.zeros((2,3))

In [18]:
zero_array

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
array_with_arange = np.arange(6)

In [20]:
array_with_arange

array([0, 1, 2, 3, 4, 5])

In [21]:
array_with_arange_with_Step_size = np.arange(2,10,2)

In [22]:
array_with_arange_with_Step_size

array([2, 4, 6, 8])

In [23]:
name = ["Ramesh","mahesh","vedika","ramu"]
maths = [79,89,89,90]
English = [90,91,97,99]
Science =[90,89,87,90]

In [24]:
import pandas as pd

arrays_to_dataframe=  pd.DataFrame({"name":name,"maths":maths,"English":English,"Science":Science} )

In [25]:
arrays_to_dataframe

name  maths  English  Science
0  Ramesh     79       90       90
1  mahesh     89       91       89
2  vedika     89       97       87
3    ramu     90       99       90

Transpose_of_array

In [26]:
array3 = np.array([[10,-7,0, 20],[-5,1,200,40],[30,1,-1,4]])

In [27]:
array3.transpose()

array([[ 10,  -5,  30],
       [ -7,   1,   1],
       [  0, 200,  -1],
       [ 20,  40,   4]])

 Sorting_array

In [28]:
array4 = np.array([1,0,2,-3,6,8,4,7])



In [29]:
array4.sort()

In [30]:
array4

array([-3,  0,  1,  2,  4,  6,  7,  8])

In [31]:
array5 = np.array([[10,-7,0, 20],[-5,1,200,40],[30,1,-1,4]])

In [32]:
array5

array([[ 10,  -7,   0,  20],
       [ -5,   1, 200,  40],
       [ 30,   1,  -1,   4]])

In [33]:
array5.sort(axis =0)
##axis =0 means column-wise sorting 

In [34]:
array5

array([[ -5,  -7,  -1,   4],
       [ 10,   1,   0,  20],
       [ 30,   1, 200,  40]])

 Concatenating Arrays

In [35]:
array1 = np.array([[10, 20], [-30,40]])


In [36]:
array1

array([[ 10,  20],
       [-30,  40]])

In [37]:
array1.shape

(2, 2)

In [38]:
array2 = np.zeros((2, 3), dtype=array1.dtype)


In [39]:
array2.shape

(2, 3)

In [40]:
array2

array([[0, 0, 0],
       [0, 0, 0]])

In [41]:
np.concatenate((array1,array2),axis = 1)
#

array([[ 10,  20,   0,   0,   0],
       [-30,  40,   0,   0,   0]])

Reshaping Arrays

In [42]:
array3 = np.arange(10,22)

In [43]:
array3.shape

(12,)

In [44]:
array3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [45]:
array3.reshape(3,4)

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [46]:
array3.reshape(6,2)

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21]])

#.        -- statistical operation

In [47]:
#let us take two arrays:
arrayA = np.array([1,0,2,-3,6,8,4,7])     
arrayB = np.array([[3,6],[4,2]])

In [48]:
arrayB

array([[3, 6],
       [4, 2]])

In [49]:
#here we can see in case of 2-D array if passing parameter axis =1 i.e columns wise and axis =0 rowwise 

In [50]:
arrayB.min(axis = 1)

array([3, 2])

In [51]:
arrayA.max()

8

In [52]:
arrayA.max()

8

In [53]:
arrayB.mean(axis = 0)

array([3.5, 4. ])

In [54]:
arrayB.mean(axis =1)

array([4.5, 3. ])

In [55]:
arrayA.std()

3.550968177835448

In [56]:
# Loading Arrays from Files
# to load that data in an array for processing. numpy.loadtxt() and numpy.genfromtxt()are the two functions that can be used to load data from text files. 
# The most commonly used file type to handle large amount of data is called CSV (Comma Separated Values)

In [57]:
# dataarray = np.genfromtxt('C:/NCERT/dataMissing.txt',skip_header=1, delimiter=',', filling_values=-999, dtype = int)
#studentdata = np.loadtxt('C:/NCERT/data.txt', skiprows=1, delimiter=',', dtype = int)


SAVING DATA TO LOCAL DRIVE 

In [58]:
#np.savetxt('C:/NCERT/testout.txt', studentdata, delimiter=',', fmt='%i')


# --casestudy on iris dataset (NCERT SOLVED)

1. Load the data in the file Iris.txt in a 2-D array called iris.
2. Drop column whose index = 4 from the array iris.
3. Display the shape, dimensions and size of iris.
4. Split iris into three 2-D arrays, each array for a different species. Call them iris1, iris2, iris3.
5. Print the three arrays iris1, iris2, iris3
6. Create a 1-D array header having elements "sepal length", "sepal width", "petal length", "petal width", "Species No" in that order.
7. Display the array header. 
8. Find the max, min, mean and standard deviation for the columns of the iris and store the results in the arrays iris_max, iris_min, iris_avg, iris_std, iris_var respectively. The results must be rounded to not more than two decimal places
9. Similarly find the max, min, mean and standard deviation for the columns of the iris1, iris2 and iris3 and store the results in the arrays with appropriate names. 
10. Check the minimum value for sepal length, sepal width, petal length and petal width of the three species in comparison to the minimum value of sepal length, sepal width, petal length and petal width for the data set as a whole and fill the table below with True if the species value is greater than the dataset value and False otherwise
11. Compare Iris setosa’s average sepal width to that of Iris virginica. 
12. Compare Iris setosa’s average petal length to that of Iris virginica. 
13. Compare Iris setosa’s average petal width to that of Iris virginica. 
14. Save the array iris_avg in a comma separated file namedIrisMeanValues.txt on the hard disk.
15. Save the arrays iris_max, iris_avg, iris_min in a comma separated file named IrisStat.txt on the hard disk.


In [59]:
df_txt = pd.read_csv('https://raw.githubusercontent.com/sagar3122/Machine-Learning/master/iris.data.txt')

In [60]:
iris_Dataset = pd.read_csv(r"D:\DS_Resources\Datasets\iris_dataset\Iris.csv")

In [61]:
# iris_data = np.loadtxt("D:\DS_Resources\Datasets\iris_dataset-master\iris.data.txt", skiprows=1, delimiter=',', dtype = float)

In [62]:
import numpy as np
#1
iris_data = np.genfromtxt("D:\DS_Resources\Datasets\iris_dataset-master\iris.data.txt",skip_header=1, delimiter=',', dtype = float)

In [63]:
iris_data

array([[4.9, 3. , 1.4, 0.2, nan],
       [4.7, 3.2, 1.3, 0.2, nan],
       [4.6, 3.1, 1.5, 0.2, nan],
       [5. , 3.6, 1.4, 0.2, nan],
       [5.4, 3.9, 1.7, 0.4, nan],
       [4.6, 3.4, 1.4, 0.3, nan],
       [5. , 3.4, 1.5, 0.2, nan],
       [4.4, 2.9, 1.4, 0.2, nan],
       [4.9, 3.1, 1.5, 0.1, nan],
       [5.4, 3.7, 1.5, 0.2, nan],
       [4.8, 3.4, 1.6, 0.2, nan],
       [4.8, 3. , 1.4, 0.1, nan],
       [4.3, 3. , 1.1, 0.1, nan],
       [5.8, 4. , 1.2, 0.2, nan],
       [5.7, 4.4, 1.5, 0.4, nan],
       [5.4, 3.9, 1.3, 0.4, nan],
       [5.1, 3.5, 1.4, 0.3, nan],
       [5.7, 3.8, 1.7, 0.3, nan],
       [5.1, 3.8, 1.5, 0.3, nan],
       [5.4, 3.4, 1.7, 0.2, nan],
       [5.1, 3.7, 1.5, 0.4, nan],
       [4.6, 3.6, 1. , 0.2, nan],
       [5.1, 3.3, 1.7, 0.5, nan],
       [4.8, 3.4, 1.9, 0.2, nan],
       [5. , 3. , 1.6, 0.2, nan],
       [5. , 3.4, 1.6, 0.4, nan],
       [5.2, 3.5, 1.5, 0.2, nan],
       [5.2, 3.4, 1.4, 0.2, nan],
       [4.7, 3.2, 1.6, 0.2, nan],
       [4.8, 3

In [64]:
#2
iris_data = iris_data[0:30,[0,1,2,3]]


In [65]:
iris_data

array([[4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2]])

In [66]:
iris_data.ndim

2

In [67]:
iris_data.shape

(30, 4)

In [68]:
# Q3
iris1,iris2,iris3 = np.split(iris_data,[10,20],axis =0)

In [69]:
#4
iris1

array([[4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2]])

In [70]:
iris2

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2]])

In [71]:
iris3

array([[5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2]])

In [72]:
#Q6 
header = np.array(["sepal length", "sepal width", "petal length", "petal width"])


In [73]:
#Q7 Priting header
print(header)

['sepal length' 'sepal width' 'petal length' 'petal width']


                              stats for iris_dataset


In [74]:
#Q8
iris_max =iris_data.max(axis =0)

In [75]:
iris_max

array([5.8, 4.4, 1.9, 0.5])

In [76]:
iris_min =iris_data.min(axis =0)

In [77]:
iris_min

array([4.3, 2.9, 1. , 0.1])

In [78]:
iris_mean =iris_data.mean(axis=0).round(2)

In [79]:
iris_mean

array([5.02, 3.44, 1.48, 0.25])

In [80]:
iris_avg = iris_data.mean(axis=0).round(2)

In [81]:
iris_std  = iris_data.std(axis = 0).round(2)

In [82]:
iris_std

array([0.37, 0.35, 0.18, 0.1 ])

In [83]:
iris1_max = iris1.max(axis=0)

In [84]:
iris1_max

array([5.4, 3.9, 1.7, 0.4])

In [85]:
iris1_min = iris1.min(axis =0)

In [86]:
iris2_max = iris2.max(axis=0)

In [87]:
iris2_max

array([5.8, 4.4, 1.7, 0.4])

In [88]:
iris3_max = iris3.max(axis=0)

In [89]:
iris1_min = iris1.min(axis=0)

In [90]:
iris3_min = iris3.min(axis=0)

In [91]:
iris1_min[0] > iris_min[0]

True

In [93]:
 #Save the array iris_avg
np.savetxt('D:\DS_Resources\IrisMeanValues.txt', iris_avg, delimiter = ',')


In [94]:
#Save the arrays iris_max
np.savetxt('D:\DS_Resources\IrisStat.txt', (iris_max, iris_avg, iris_min), delimiter=',')